language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key: f905331b6149d6abe03629c65fd15007
  app: https://boiling-hamlet-64107.herokuapp.com/
  run: rails db:migrate
