# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
user_1 = User.create(name: 'Jackie Chan', email: 'j', password: 'j', password_confirmation: 'j')
user_2 = User.create(name: 'Cynthia Rothrock', email: 'c', password: 'c', password_confirmation: 'c')
user_3 = User.create(name: 'Michelle Yeoh', email: 'm', password: 'm', password_confirmation: 'm')
user_4 = User.create(name: 'Bilbo Baggins', email: 'b', password: 'b', password_confirmation: 'b')
user_5 = User.create(name: 'Gandolf', email: 'g', password: 'g', password_confirmation: 'g')
user_6 = User.create(name: 'Sneezy', email: 's', password: 's', password_confirmation: 's')
user_7 = User.create(name: 'WTF', email: 'w', password: 'w', password_confirmation: 'w')

friendship_1 = Friendship.create(user_id: user_1.id, friend_id: user_2.id)
friendship_2 = Friendship.create(user_id: user_2.id, friend_id: user_1.id)
friendship_3 = Friendship.create(user_id: user_1.id, friend_id: user_3.id)
friendship_4 = Friendship.create(user_id: user_3.id, friend_id: user_1.id)
friendship_5 = Friendship.create(user_id: user_1.id, friend_id: user_4.id)
friendship_6 = Friendship.create(user_id: user_4.id, friend_id: user_1.id)
friendship_7 = Friendship.create(user_id: user_2.id, friend_id: user_3.id)
friendship_8 = Friendship.create(user_id: user_3.id, friend_id: user_2.id)
friendship_9 = Friendship.create(user_id: user_2.id, friend_id: user_5.id)
friendship_10 = Friendship.create(user_id: user_5.id, friend_id: user_2.id)

party_1 = Party.create(movie_title: "The Exorcist III", user_id: user_1.id, date: "October 26th, 1997", time: "1:45pm")
party_2 = Party.create(movie_title: "Psycho II", user_id: user_1.id, date: "June 2nd, 1998", time: "2:45pm")
party_3 = Party.create(movie_title: "Hellbound: Hellraiser II", user_id: user_1.id, date: "September 22nd, 1999", time: "3:45pm")
party_4 = Party.create(movie_title: "House II: The Second Story", user_id: user_2.id, date: "April 22nd, 2000", time: "4:45pm")
party_5 = Party.create(movie_title: "The Gate II", user_id: user_2.id, date: "January 19nd, 2001", time: "5:45pm")
party_6 = Party.create(movie_title: "Ip Man II", user_id: user_2.id, date: "July 1nd, 2002", time: "6:45pm")
party_7 = Party.create(movie_title: "The Fortress II", user_id: user_3.id, date: "January 7th, 2003", time: "7:45pm")

party_user_1 = PartyUser.create(party_id: party_1.id, user_id: user_2.id, status: 2)
party_user_2 = PartyUser.create(party_id: party_1.id, user_id: user_3.id, status: 2)
party_user_3 = PartyUser.create(party_id: party_2.id, user_id: user_2.id, status: 2)
party_user_4 = PartyUser.create(party_id: party_2.id, user_id: user_4.id, status: 0)
party_user_5 = PartyUser.create(party_id: party_3.id, user_id: user_3.id, status: 1)
party_user_6 = PartyUser.create(party_id: party_3.id, user_id: user_4.id, status: 0)
party_user_7 = PartyUser.create(party_id: party_4.id, user_id: user_1.id, status: 1)
party_user_8 = PartyUser.create(party_id: party_4.id, user_id: user_3.id, status: 0)
party_user_9 = PartyUser.create(party_id: party_5.id, user_id: user_1.id, status: 2)
party_user_10 = PartyUser.create(party_id: party_5.id, user_id: user_5.id, status: 2)
party_user_11 = PartyUser.create(party_id: party_6.id, user_id: user_2.id, status: 2)
party_user_12 = PartyUser.create(party_id: party_6.id, user_id: user_5.id, status: 2)
party_user_13 = PartyUser.create(party_id: party_7.id, user_id: user_1.id, status: 0)
